### ISSUE TITLE
certain file names prevent use in Windows dev environments

### ISSUE THREAD

**Issue by paoda** [mattyhall/tomlz#13]
I recently got around to trying to figure out why only Windows builds of my project weren't building. I originally assumed it had something to do with Zig's cache system since I recently switched over to the package manager and so I opened an issue https://github.com/ziglang/zig/issues/16523

Armed with a debug version of the compiler I eventually realized that the issue has to do with an inability to create a select few files in this repository. [This one in particular](https://github.com/mattyhall/tomlz/blob/main/tests/fuzzing/id%3A000000%2Csig%3A06%2Csrc%3A000024%2Ctime%3A10060%2Cexecs%3A1850%2Cop%3Ahavoc%2Crep%3A4) and others like it prevented my project from being built.

**Comment by mattyhall** [comment]
Hi @paoda, thanks for raising this issue. I have a few questions:
1. Does the problem occur when you depend on the package using the new package manager?
2. If so, what error message do you get when trying to build your project?
3. Could you try to clone this repo and then run `zig build test` please? If there are any errors please post them.

Given the filename is 65 characters long I wonder whether we are hitting `MAX_PATH` limitations here. On Windows the maximum path length is [260 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry).

**Comment by rohlem** [comment]
> Given the filename is 65 characters long [...]

Just drive-by-commenting, but I think the issue is rather that `:` is an unsupported(/unexpected?) character in file names under Windows - probably reserved for drive selection syntax `C:\` etc. .

**Comment by paoda** [comment]
Hello! @mattyhall. Thanks for all the work done in this library! 

1. Yes it does occur when I depend on the package using the new package manager.
2. It's not a very helpful one. It's `error.Unexpected`. Hopefully https://github.com/ziglang/zig/issues/16523#issuecomment-1648821448 can give a bit more context as to why/where the error is occuring. 
3. Understanding that `MAX_PATH` may be involved, I cloned to repo to `C:\dev` hoping to keep the path as short as possible. I was not able to clone the repo. The output is below: 

```
 C:\dev                                                                                                                                                                                             | 18:19:47
➜ git clone https://github.com/mattyhall/tomlz
Cloning into 'tomlz'...
remote: Enumerating objects: 997, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (112/112), done.
Receiving objects: 100% (997/997)used 118 (delta 55), pack-reused 823
Receiving objects: 100% (997/997), 164.49 KiB | 979.00 KiB/s, done.
Resolving deltas: 100% (358/358), done.
error: invalid path 'tests/fuzzing/id:000000,sig:06,src:000024,time:10060,execs:1850,op:havoc,rep:4'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

rohlem's explanation makes sense to me! [`:` is indeed reserved on windows.](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)

**Comment by mattyhall** [comment]
Thanks @rohlem - TIL. Drive-by comments are always welcome, especially if they fix an issue ;)

@paoda thanks for reproducing. I've just pushed a commit to main that replaces the colons with hyphens. I'll close this issue now but if it still doesn't work feel free to reopen.

Cheers both
