### ISSUE TITLE
Optional Value With Default?

### ISSUE THREAD

**Issue by jcalabro** [mattyhall/tomlz#16]
Hey there, this library looks great!

One question on it: is there a way to disable `DecodingError.MissingField` if there are defaults provided on the struct definition and the provided toml doesn't declare the value?

For example, I'd love if this didn't throw `error: MissingField` and instead gave me a `MyStruct` object with `a = "a from file"` and `b = "b"`:

```zig
const std = @import("std");
const tomlz = @import("tomlz");

pub const MyStruct = struct {
    a: []const u8 = "a",
    b: []const u8 = "b",
};

pub fn main() !void {
    var gpa = std.heap.page_allocator;

    var s = try tomlz.decode(MyStruct, gpa,
        \\a = "a from file"
    );

    std.debug.print("{any}\n", .{s});
}
```

**Comment by mattyhall** [comment]
Hey, I’m afraid that doesn’t work currently but it’s a great idea. I will try to get round to adding it this week

**Comment by jcalabro** [comment]
No pressure or anything, just thought it might be neat!
