### ISSUE TITLE
Serializing paths on windows doesn't escape backslash

### ISSUE THREAD

**Issue by coodeneko** [mattyhall/tomlz#21]
I'm using the serialize to store a path into a toml file. However when trying to parse that file back it fails. Looks like the serialize doesn't escape the backslash. For examples here is a generated toml. I tried both serialize with a wrapping struct and serializeKeyValue with the same results. The exe_path is stored in  a []u8.

```
exe_path = "D:\Projects\output\Runner.exe"
```

**Comment by 0x5a4** [comment]
i'll have a look at this on the weekend, should be pretty straight forward 👍

**Comment by mattyhall** [comment]
Thanks @0x5a4, should just need to do the inverse of [`parseEscapeChar`](https://github.com/mattyhall/tomlz/blob/9a16dd53927ef2012478b6494bafb4475e44f4c9/src/lexer.zig#L159), or perhaps use [literal strings](https://toml.io/en/#:~:text=Literal%20strings%20are%20surrounded%20by%20single%20quotes.%20No%20escaping%20is%20performed%20so%20what%20you%20see%20is%20what%20you%20get%3A).
